import test from "node:test";
import assert from "node:assert/strict";
import {canonicalize} from "../services/local-repository.js";
import {resolveExclusiveGroupProgress,validateExclusiveProgram} from "../services/cashback-exclusive.js";
import {calculateProgress} from "../services/cashback-progress.js";
import {recommendOrders} from "../services/order-coordination.js";

const programs=[
 {id:"market",bankCardProductId:"p",name:"Siêu thị / Tạp hóa",rate:6.8,maxCashback:680000,eligibleTarget:10000000,exclusiveMode:"first_reached",exclusiveGroupId:"SACOM_CB_MAIN",mccSelectionMode:"all",status:"active"},
 {id:"travel",bankCardProductId:"p",name:"Đi lại",rate:16.8,maxCashback:680000,eligibleTarget:4047619,exclusiveMode:"first_reached",exclusiveGroupId:"SACOM_CB_MAIN",mccSelectionMode:"all",status:"active"}
];
const card={id:"cc",cardProductId:"p",customerId:"c",status:"active"},product={id:"p",cashbackCycleMode:"monthly"},cycle={start:"2026-09-01",end:"2026-09-30"};
const tx=(id,date,programId,amount,customerCardId="cc",createdAt)=>({id,date,customerCardId,cashbackProgramId:programId,amount,status:"completed",mccCategoryId:"m",transactionMethod:"Online",...(createdAt?{createdAt}:{})});

test("old program migrates to independent idempotently",()=>{const data=canonicalize({customers:[{id:"c"}],cardProducts:[{id:"p"}],customerCards:[card],mccCategories:[{id:"m",name:"M"}],cashbackPrograms:[{...programs[0],exclusiveMode:undefined,exclusiveGroupId:undefined}]});assert.equal(data.cashbackPrograms[0].exclusiveMode,"none");assert.equal(data.cashbackPrograms[0].exclusiveGroupId,null);assert.deepEqual(canonicalize(data),data);});
test("exclusive validation requires target/group and rejects cross Card ID",()=>{assert.equal(validateExclusiveProgram({...programs[0],exclusiveGroupId:""},programs).valid,false);assert.equal(validateExclusiveProgram({...programs[0],maxCashbackUnlimited:true,eligibleTarget:null},programs).valid,false);assert.equal(validateExclusiveProgram({...programs[0],id:"x",bankCardProductId:"other"},programs).valid,false);});
test("transportation reaches first; loser locked and only winner cashback counts",()=>{const transactions=[tx("m1","2026-09-01","market",6000000,"cc","2026-09-01T08:00:00Z"),tx("t1","2026-09-05","travel",4047619,"cc","2026-09-05T08:00:00Z"),tx("m2","2026-09-10","market",4000000,"cc","2026-09-10T08:00:00Z")],r=resolveExclusiveGroupProgress({programs,transactions,customerCard:card,cycle});assert.equal(r.winnerProgramId,"travel");assert.equal(r.programs.market.status,"locked");const pp=programs.map(program=>calculateProgress({customerCard:card,product,program,programs,transactions,referenceDate:"2026-09-15"}));assert.equal(pp.find(x=>x.programId==="market").cashbackEarned,0);assert.equal(pp.find(x=>x.programId==="travel").cashbackEarned,680000);});
test("other side wins and delete recalculates",()=>{const transactions=[tx("m1","2026-09-03","market",10000000,"cc","2026-09-03T08:00:00Z"),tx("t1","2026-09-05","travel",4047619,"cc","2026-09-05T08:00:00Z")];assert.equal(resolveExclusiveGroupProgress({programs,transactions,customerCard:card,cycle}).winnerProgramId,"market");assert.equal(resolveExclusiveGroupProgress({programs,transactions:transactions.slice(1),customerCard:card,cycle}).winnerProgramId,"travel");});
test("no winner, next cycle and customer cards are independent",()=>{const partial=[tx("m","2026-09-01","market",5000000),tx("t","2026-09-02","travel",2000000)];assert.equal(resolveExclusiveGroupProgress({programs,transactions:partial,customerCard:card,cycle}).winnerProgramId,null);assert.equal(resolveExclusiveGroupProgress({programs,transactions:partial,customerCard:card,cycle:{start:"2026-10-01",end:"2026-10-31"}}).winnerProgramId,null);const other={...card,id:"cc2"},mixed=[tx("a","2026-09-03","travel",4047619),tx("b","2026-09-02","market",10000000,"cc2")];assert.equal(resolveExclusiveGroupProgress({programs,transactions:mixed,customerCard:card,cycle}).winnerProgramId,"travel");assert.equal(resolveExclusiveGroupProgress({programs,transactions:mixed,customerCard:other,cycle}).winnerProgramId,"market");});
test("same date without sequence becomes tie and awards neither",()=>{const transactions=[tx("a","2026-09-03","market",10000000),tx("b","2026-09-03","travel",4047619)],r=resolveExclusiveGroupProgress({programs,transactions,customerCard:card,cycle});assert.equal(r.status,"needs-confirmation");assert.equal(r.winnerProgramId,null);for(const program of programs)assert.equal(calculateProgress({customerCard:card,product,program,programs,transactions,referenceDate:"2026-09-15"}).cashbackEarned,0);});
test("recommendation prefers candidate closing group then smallest remaining",()=>{const state={customers:[{id:"c",fullName:"A"}],customerCards:[card],cardProducts:[product],cashbackPrograms:programs,transactions:[tx("m","2026-09-01","market",6000000),tx("t","2026-09-02","travel",3500000)]};const rows=recommendOrders(state,{amount:600000,mccCategoryId:"m",transactionMethod:"Online",referenceDate:"2026-09-15"});assert.equal(rows[0].program.id,"travel");assert.equal(rows[0].wouldWinExclusive,true);});
