import test from "node:test";
import assert from "node:assert/strict";
import {canonicalize,LocalRepository} from "../services/local-repository.js";
import {calculateCashbackCycle} from "../services/cashback-cycle.js";
import {calculateProgress} from "../services/cashback-progress.js";
import {recommendOrders} from "../services/order-coordination.js";

test("monthly and statement cycle boundaries",()=>{
 assert.deepEqual(calculateCashbackCycle({mode:"monthly",referenceDate:"2026-02-14"}),{valid:true,mode:"monthly",start:"2026-02-01",end:"2026-02-28"});
 assert.equal(calculateCashbackCycle({mode:"monthly",referenceDate:"2024-02-14"}).end,"2024-02-29");
 assert.deepEqual(calculateCashbackCycle({mode:"statement",statementDay:20,referenceDate:"2026-08-21"}),{valid:true,mode:"statement",start:"2026-08-21",end:"2026-09-20"});
 assert.deepEqual(calculateCashbackCycle({mode:"statement",statementDay:1,referenceDate:"2027-01-01"}),{valid:true,mode:"statement",start:"2026-12-02",end:"2027-01-01"});
 assert.equal(calculateCashbackCycle({mode:"statement",statementDay:31,referenceDate:"2024-02-15"}).end,"2024-02-29");
 for(const day of [28,30,31])assert.equal(calculateCashbackCycle({mode:"statement",statementDay:day,referenceDate:"2026-12-31"}).valid,true);
 assert.equal(calculateCashbackCycle({mode:"statement",referenceDate:"2026-08-01"}).valid,false);
});

const base=canonicalize({revision:7,settings:{keep:true},banks:[{id:"b",code:"HDB",name:"HDBank"}],customers:[{id:"c",customerCode:"KH-1",fullName:"An"}],cardProducts:[{id:"p",cardId:"HDB-GOLD",bankId:"b",cardName:"Gold",cashbackCycleMode:"monthly"}],customerCards:[{id:"cc",customerId:"c",cardProductId:"p",statementDay:20}],mccCategories:[{id:"m",name:"Online",codes:["5411"]}],cashbackPrograms:[{id:"pr",bankCardProductId:"p",name:"Max CB Online",mccCategoryIds:["m"],transactionMethod:"Online",rate:10,maxCashback:400000}],transactions:[{id:"t",date:"2026-08-10",customerId:"c",customerCardId:"cc",amount:2650000,mccCategoryId:"m",transactionMethod:"Online",cashbackProgramId:"pr",status:"completed"},{id:"x",date:"2026-08-11",customerId:"c",customerCardId:"cc",amount:1000000,mccCategoryId:"m",transactionMethod:"Online",cashbackProgramId:"pr",status:"cancelled"}]});
test("migration is idempotent and preserves IDs/revision/settings",()=>{const twice=canonicalize(base);assert.deepEqual(twice,base);assert.equal(twice.schemaVersion,3);assert.equal(twice.customers[0].id,"c");assert.equal(twice.customerCards[0].id,"cc");assert.equal(twice.revision,7);assert.equal(twice.settings.keep,true);});
test("localStorage serialization roundtrip",()=>{const memory=new Map();globalThis.localStorage={getItem:key=>memory.get(key)??null,setItem:(key,value)=>memory.set(key,value)};const repo=new LocalRepository(),saved=repo.save(base,{dirty:false,notify:false}),loaded=repo.load();assert.deepEqual(loaded,saved);assert.equal(loaded.cashbackPrograms[0].bankCardProductId,"p");assert.equal(loaded.transactions[0].customerCardId,"cc");});
test("capped, cancelled exclusion, targets and recommendation",()=>{const p=calculateProgress({customerCard:base.customerCards[0],product:base.cardProducts[0],program:base.cashbackPrograms[0],transactions:base.transactions,programs:base.cashbackPrograms,referenceDate:"2026-08-15"});assert.equal(p.eligibleSpend,2650000);assert.equal(p.cashbackEarned,265000);assert.equal(p.remainingEligibleSpend,1350000);const rec=recommendOrders(base,{amount:1000000,mccCategoryId:"m",transactionMethod:"Online",referenceDate:"2026-08-15"});assert.equal(rec[0].incrementalCashback,100000);assert.equal(rec[0].remainingAfter,350000);});
test("unlimited and independent total target",()=>{const program={...base.cashbackPrograms[0],id:"u",maxCashbackUnlimited:true,maxCashback:null,eligibleTarget:null,totalTarget:3000000};const tx=base.transactions.map(x=>({...x,cashbackProgramId:"u"}));const p=calculateProgress({customerCard:base.customerCards[0],product:base.cardProducts[0],program,transactions:tx,programs:[program],referenceDate:"2026-08-15"});assert.equal(p.cashbackEarned,265000);assert.equal(p.remainingEligibleSpend,null);assert.equal(p.remainingTotalSpend,350000);});
test("shared cap does not double count",()=>{const a={...base.cashbackPrograms[0],id:"a",sharedCashbackGroup:"g",maxCashback:400000},b={...a,id:"b"},tx=[{...base.transactions[0],id:"a1",cashbackProgramId:"a",amount:3000000},{...base.transactions[0],id:"b1",cashbackProgramId:"b",amount:3000000}];const pa=calculateProgress({customerCard:base.customerCards[0],product:base.cardProducts[0],program:a,transactions:tx,programs:[a,b],referenceDate:"2026-08-15"}),pb=calculateProgress({customerCard:base.customerCards[0],product:base.cardProducts[0],program:b,transactions:tx,programs:[a,b],referenceDate:"2026-08-15"});assert.ok(pa.cashbackEarned+pb.cashbackEarned<=400000);});
