import test from "node:test";
import assert from "node:assert/strict";
import {calculateCashbackTarget} from "../services/cashback-feature-ui.js";
import {calculateProgress} from "../services/cashback-progress.js";
import {resolveExclusiveGroupProgress} from "../services/cashback-exclusive.js";
import {canonicalize,LocalRepository} from "../services/local-repository.js";
import {recommendOrders} from "../services/order-coordination.js";

const product={id:"cake",cashbackCycleMode:"monthly"},card={id:"cc",cardProductId:"cake",customerId:"c",status:"active"},cake={id:"premium",bankCardProductId:"cake",name:"Cake Premium",rate:20,maxCashback:2000000,maxCashbackUnlimited:false,eligibleTarget:10000000,totalTarget:20000000,mccSelectionMode:"selected",mccCategoryIds:["eligible"],excludedMccCategoryIds:[],exclusiveMode:"none",exclusiveGroupId:null,status:"active"};
const tx=(id,date,amount,mccCategoryId="eligible",cashbackProgramId="premium")=>({id,date,amount,mccCategoryId,cashbackProgramId,customerCardId:"cc",status:"completed",transactionMethod:"Online",timestamp:`${date}T08:00:00Z`});
const progress=transactions=>calculateProgress({customerCard:card,product,program:cake,programs:[cake],transactions,referenceDate:"2026-09-20"});

test("eligible target auto formula does not imply total target",()=>{assert.equal(calculateCashbackTarget(20,2000000),10000000);assert.equal(calculateCashbackTarget(6.8,680000),10000000);assert.equal(calculateCashbackTarget(16.8,680000),4047619);});
test("Cake A: group reached but total spend remains",()=>{const p=progress([tx("e","2026-09-05",10000000),tx("o","2026-09-06",5000000,"other","")]);assert.equal(p.eligibleTargetReached,true);assert.equal(p.totalTargetReached,false);assert.equal(p.programConditionReached,false);assert.equal(p.remainingEligibleSpend,0);assert.equal(p.remainingTotalSpend,5000000);assert.equal(p.status,"incomplete");assert.equal(p.cashbackQualifiedAmount,0);});
test("Cake B: total reached but group spend remains",()=>{const p=progress([tx("e","2026-09-05",8000000),tx("o","2026-09-06",12000000,"other","")]);assert.equal(p.eligibleSpend,8000000);assert.equal(p.totalCardSpend,20000000);assert.equal(p.eligibleTargetReached,false);assert.equal(p.totalTargetReached,true);assert.equal(p.programConditionReached,false);assert.equal(p.remainingEligibleSpend,2000000);assert.equal(p.remainingTotalSpend,0);});
test("Cake C: both conditions reached",()=>{const p=progress([tx("e","2026-09-05",10000000),tx("o","2026-09-06",10000000,"other","")]);assert.equal(p.programConditionReached,true);assert.equal(p.status,"completed");assert.equal(p.cashbackQualifiedAmount,2000000);});
test("program without total target depends only on eligible target",()=>{const program={...cake,totalTarget:null},p=calculateProgress({customerCard:card,product,program,programs:[program],transactions:[tx("e","2026-09-05",10000000)],referenceDate:"2026-09-20"});assert.equal(p.totalTargetReached,true);assert.equal(p.programConditionReached,true);});
test("unlimited program with manual total target depends on total only",()=>{const program={...cake,maxCashbackUnlimited:true,maxCashback:null,eligibleTarget:null,totalTarget:20000000},p=calculateProgress({customerCard:card,product,program,programs:[program],transactions:[tx("o","2026-09-06",20000000,"other","")],referenceDate:"2026-09-20"});assert.equal(p.eligibleTarget,null);assert.equal(p.eligibleTargetReached,true);assert.equal(p.totalTargetReached,true);assert.equal(p.programConditionReached,true);});
test("exclusive reachedAt waits for both thresholds",()=>{const a={...cake,id:"a",exclusiveMode:"first_reached",exclusiveGroupId:"G",eligibleTarget:10000000,totalTarget:20000000},b={...cake,id:"b",exclusiveMode:"first_reached",exclusiveGroupId:"G",eligibleTarget:4000000,totalTarget:null},transactions=[tx("a1","2026-09-05",10000000,"eligible","a"),tx("b1","2026-09-08",4000000,"eligible","b"),tx("o","2026-09-10",6000000,"other","")],r=resolveExclusiveGroupProgress({programs:[a,b],transactions,customerCard:card,cycle:{start:"2026-09-01",end:"2026-09-30"}});assert.equal(r.programs.a.reachedAt,"2026-09-10T08:00:00.000Z");assert.equal(r.programs.b.reachedAt,"2026-09-08T08:00:00.000Z");assert.equal(r.winnerProgramId,"b");});
test("ineligible proposed order still advances total spend",()=>{const state={customers:[{id:"c",fullName:"C"}],customerCards:[card],cardProducts:[product],cashbackPrograms:[cake],transactions:[tx("e","2026-09-05",10000000)]},rec=recommendOrders(state,{amount:10000000,mccCategoryId:"other",transactionMethod:"Online",referenceDate:"2026-09-20"})[0];assert.equal(rec.eligibleAmount,0);assert.equal(rec.totalSpendAmount,10000000);assert.equal(rec.remainingTotalAfter,0);assert.equal(rec.wouldMeetConditions,true);});
test("repository roundtrip preserves eligible and total target",()=>{const raw={customers:[{id:"c"}],cardProducts:[product],customerCards:[card],mccCategories:[{id:"eligible",name:"Eligible"}],cashbackPrograms:[cake]},state=canonicalize(raw),memory=new Map();globalThis.localStorage={getItem:key=>memory.get(key)??null,setItem:(key,value)=>memory.set(key,value)};globalThis.CustomEvent??=class CustomEvent extends Event{constructor(type,options={}){super(type);this.detail=options.detail;}};const repo=new LocalRepository(),loaded=(repo.save(state,{dirty:false,notify:false}),repo.load());assert.equal(loaded.cashbackPrograms[0].eligibleTarget,10000000);assert.equal(loaded.cashbackPrograms[0].totalTarget,20000000);});
