import test from "node:test";
import assert from "node:assert/strict";
import {applyExclusiveProgramSelection,exclusiveProgramOptions,selectedExclusiveProgramIds} from "../services/cashback-exclusive.js";
import {canonicalize} from "../services/local-repository.js";

const p=(id,name,card="card",group=null)=>({id,name,bankCardProductId:card,rate:10,maxCashback:100,eligibleTarget:1000,status:"active",exclusiveMode:group?"first_reached":"none",exclusiveGroupId:group});
test("options filter same Card ID, exclude current and sort Vietnamese names",()=>{const values=[p("a","Zeta"),p("b","Ăn uống"),p("c","Đi lại"),p("x","Khác","other")],options=exclusiveProgramOptions(values,"card","a");assert.deepEqual(options.map(x=>x.id),["b","c"]);});
test("new A selects B creates one stable group",()=>{const result=applyExclusiveProgramSelection({programs:[p("b","B")],currentProgram:p("a","A","card","temporary"),selectedProgramIds:["b"],makeId:()=>"stable"});assert.equal(result.valid,true);assert.equal(result.groupId,"EXG_stable");assert.equal(new Set(result.programs.map(x=>x.exclusiveGroupId)).size,1);});
test("A joins B and C existing group",()=>{const result=applyExclusiveProgramSelection({programs:[p("b","B","card","GX"),p("c","C","card","GX")],currentProgram:{...p("a","A"),exclusiveMode:"first_reached"},selectedProgramIds:["b"]});assert.ok(result.programs.every(x=>x.exclusiveGroupId==="GX"));});
test("merge multiple groups deterministically",()=>{const values=[p("b","B","card","GY"),p("d","D","card","GY"),p("c","C","card","GX"),p("e","E","card","GX")],result=applyExclusiveProgramSelection({programs:values,currentProgram:{...p("a","A"),exclusiveMode:"first_reached"},selectedProgramIds:["b","c"]});assert.equal(result.groupId,"GX");assert.ok(result.programs.every(x=>x.exclusiveGroupId==="GX"));});
test("edit restore and removing C rebuilds A selection",()=>{const values=[p("a","A","card","GX"),p("b","B","card","GX"),p("c","C","card","GX")];assert.deepEqual(selectedExclusiveProgramIds(values[0],values),["b","c"]);const result=applyExclusiveProgramSelection({programs:values,currentProgram:values[0],selectedProgramIds:["b"]});assert.equal(result.programs.find(x=>x.id==="a").exclusiveGroupId,"GX");assert.equal(result.programs.find(x=>x.id==="b").exclusiveGroupId,"GX");assert.equal(result.programs.find(x=>x.id==="c").exclusiveMode,"none");});
test("switch independent normalizes remaining singleton",()=>{const values=[p("a","A","card","GX"),p("b","B","card","GX")],result=applyExclusiveProgramSelection({programs:values,currentProgram:{...values[0],exclusiveMode:"none"},selectedProgramIds:[]});assert.ok(result.programs.every(x=>x.exclusiveMode==="none"&&x.exclusiveGroupId===null));});
test("invalid selection and empty selection are rejected",()=>{assert.equal(applyExclusiveProgramSelection({programs:[p("x","X","other")],currentProgram:p("a","A","card","temp"),selectedProgramIds:["x"]}).valid,false);assert.equal(applyExclusiveProgramSelection({programs:[],currentProgram:p("a","A","card","temp"),selectedProgramIds:[]}).valid,false);});
test("serialization keeps exclusiveGroupId canonical without duplicate relationship fields",()=>{const raw={customers:[],cardProducts:[{id:"card"}],mccCategories:[],cashbackPrograms:[p("a","A","card","GX"),p("b","B","card","GX")]},state=canonicalize(raw),again=canonicalize(state);assert.equal(again.cashbackPrograms[0].exclusiveGroupId,"GX");assert.equal("exclusiveProgramIds" in again.cashbackPrograms[0],false);});
