import test from "node:test";
import assert from "node:assert/strict";
import {canonicalize,LocalRepository} from "../services/local-repository.js";
import {isProgramMccEligible,normalizeProgramMccSelection} from "../services/cashback-program.js";
import {isProgramEligible,calculateProgress} from "../services/cashback-progress.js";
import {recommendOrders} from "../services/order-coordination.js";

const selected={id:"selected",mccCategoryIds:["a","b"]};
const all={id:"all",mccSelectionMode:"all",excludedMccCategoryIds:[]};
const exceptB={...all,excludedMccCategoryIds:["b"]};

test("legacy selected IDs migrate without changing program ID",()=>{const value=normalizeProgramMccSelection(selected);assert.deepEqual(value,{mccSelectionMode:"selected",eligibleMccCategoryIds:["a","b"],excludedMccCategoryIds:[]});assert.equal(selected.id,"selected");});
test("selected, all and all-except modes have explicit semantics",()=>{assert.equal(isProgramMccEligible(selected,"a"),true);assert.equal(isProgramMccEligible(selected,"c"),false);for(const id of ["a","b","c","d"])assert.equal(isProgramMccEligible(all,id),true);assert.equal(isProgramMccEligible(exceptB,"a"),true);assert.equal(isProgramMccEligible(exceptB,"b"),false);assert.equal(isProgramMccEligible(exceptB,"c"),true);});
test("a newly created MCC is automatically eligible in all mode",()=>{const program={...all},before=["a","b","c"];assert.ok(before.every(id=>isProgramMccEligible(program,id)));before.push("d");assert.equal(isProgramMccEligible(program,"d"),true);});

const raw={banks:[{id:"bank",code:"CAKE",name:"Cake"}],customers:[{id:"customer",customerCode:"KH",fullName:"An"}],cardProducts:[{id:"product",cardId:"CAKE",bankId:"bank",cardName:"Cake Premium Signature"}],customerCards:[{id:"card",customerId:"customer",cardProductId:"product",status:"active"}],mccCategories:[{id:"a",name:"Ăn uống",codes:["5814"]},{id:"b",name:"Giáo dục",codes:["8211"]},{id:"c",name:"Siêu thị",codes:["5411"]}],cashbackPrograms:[{...exceptB,id:"program",bankCardProductId:"product",name:"All except B",status:"active",rate:10,maxCashback:100000}],transactions:[{id:"ta",date:"2026-09-01",customerId:"customer",customerCardId:"card",amount:100000,mccCategoryId:"a",cashbackProgramId:"program",status:"completed"},{id:"tb",date:"2026-09-02",customerId:"customer",customerCardId:"card",amount:100000,mccCategoryId:"b",cashbackProgramId:"program",status:"completed"}]};
test("transaction, progress and coordination recommendation respect exclusions",()=>{const state=canonicalize(raw),program=state.cashbackPrograms[0];assert.equal(isProgramEligible(program,state.transactions[0]),true);assert.equal(isProgramEligible(program,state.transactions[1]),false);const progress=calculateProgress({customerCard:state.customerCards[0],product:state.cardProducts[0],program,transactions:state.transactions,programs:state.cashbackPrograms,referenceDate:"2026-09-10"});assert.equal(progress.eligibleSpend,100000);assert.equal(recommendOrders(state,{amount:50000,mccCategoryId:"b",referenceDate:"2026-09-10"}).length,0);assert.equal(recommendOrders(state,{amount:50000,mccCategoryId:"c",referenceDate:"2026-09-10"}).length,1);});
test("canonical/local roundtrip preserves the semantic MCC model",()=>{const state=canonicalize(raw),again=canonicalize(state),program=again.cashbackPrograms[0];assert.equal(program.mccSelectionMode,"all");assert.deepEqual(program.eligibleMccCategoryIds,[]);assert.deepEqual(program.excludedMccCategoryIds,["b"]);const memory=new Map();globalThis.localStorage={getItem:key=>memory.get(key)??null,setItem:(key,value)=>memory.set(key,value)};globalThis.CustomEvent??=class CustomEvent extends Event{constructor(type,options={}){super(type);this.detail=options.detail;}};const repo=new LocalRepository(),loaded=(repo.save(state,{dirty:false,notify:false}),repo.load());assert.deepEqual(loaded.cashbackPrograms[0].excludedMccCategoryIds,["b"]);});
