import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {calculateProgress} from "../services/cashback-progress.js";
import {customerCardCycleConfig,effectiveCashbackCycleMode} from "../services/cashback-cycle.js";
import {canonicalize} from "../services/local-repository.js";

const product={id:"uob",cardId:"UOB-One",cashbackCycleMode:"statement",defaultStatementDay:27},program={id:"pr",bankCardProductId:"uob",name:"UOB",rate:10,maxCashback:100000,eligibleTarget:1000000,mccSelectionMode:"all",status:"active"},progress=(card,referenceDate="2026-09-10")=>calculateProgress({customerCard:card,product,program,programs:[program],transactions:[],referenceDate});
test("same Card ID uses each customer card statement day",()=>{const a=progress({id:"a",cardProductId:"uob",statementDay:5}),b=progress({id:"b",cardProductId:"uob",statementDay:18});assert.notEqual(a.cycleStart,b.cycleStart);assert.notEqual(a.cycleEnd,b.cycleEnd);assert.notEqual(a.daysRemaining,b.daysRemaining);assert.equal(a.cycleEnd,"2026-10-05");assert.equal(b.cycleEnd,"2026-09-18");});
test("missing customer statement day never falls back to product default",()=>{const value=progress({id:"a",cardProductId:"uob",statementDay:""});assert.equal(value.status,"configuration-incomplete");assert.equal(value.warning,"Chưa cấu hình ngày sao kê cho thẻ của khách hàng này.");});
test("monthly ignores customer and product statement days",()=>{const monthly={...product,cashbackCycleMode:"monthly"},card={id:"a",cardProductId:"uob",statementDay:20},value=calculateProgress({customerCard:card,product:monthly,program,programs:[program],transactions:[],referenceDate:"2026-09-10"});assert.equal(value.cycleStart,"2026-09-01");assert.equal(value.cycleEnd,"2026-09-30");});
test("customer override determines effective mode",()=>{assert.equal(effectiveCashbackCycleMode({cashbackCycleModeOverride:"statement"},{cashbackCycleMode:"monthly"}),"statement");assert.deepEqual(customerCardCycleConfig({cashbackCycleModeOverride:"statement",statementDay:15},{cashbackCycleMode:"monthly"}),{mode:"statement",statementDay:15,statementDayRequired:true});assert.equal(effectiveCashbackCycleMode({cashbackCycleModeOverride:"monthly"},product),"monthly");assert.equal(customerCardCycleConfig({cashbackCycleModeOverride:"monthly",statementDay:15},product).statementDay,"");});
test("migration preserves legacy product day but never copies it to customer cards",()=>{const state=canonicalize({customers:[{id:"c"}],cardProducts:[product],customerCards:[{id:"cc",customerId:"c",cardProductId:"uob"}]});assert.equal(state.cardProducts[0].defaultStatementDay,27);assert.equal(state.customerCards[0].statementDay,"");assert.deepEqual(canonicalize(state),state);});
test("product UI has no default statement field and customer label is Hạn thanh toán",()=>{const source=readFileSync(new URL("../app.js",import.meta.url),"utf8");assert.equal(source.includes('selectField("defaultStatementDay","Ngày sao kê mặc định"'),false);assert.equal(source.includes('selectField("paymentDueDay","Ngày đến hạn"'),false);assert.equal(source.includes('selectField("paymentDueDay","Hạn thanh toán"'),true);});
