import {formatMoney,parseMoney,bindVndInput} from "./money.js";
import {formatDate} from "./date.js";
import {buildCoordinationRows,buildCoordinationRowsForSelection,recommendOrders} from "./order-coordination.js?v=20260901-cashback-rate-decimal-v7";
import {getProgramPriority,getMccSelectionMode} from "./cashback-program.js?v=20260901-cashback-rate-decimal-v7";

const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const normalize=value=>String(value??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/đ/g,"d").toLowerCase();
const money=value=>formatMoney(value,true);
const STATUS={urgent:"Cần đánh gấp",needed:"Cần đánh",near:"Gần đạt",completed:"Đã max",configuration:"Thiếu cấu hình"};
export const COORDINATION_THRESHOLDS={urgentDays:3,nearPercent:80};
export const coordinationUi={activeTab:"reminders",selectedCardProductId:"",selectedProgramId:"",customerSearch:"",statusFilter:"",sortMode:"priority",focusCustomerCardId:""};

export function coordinationDisplayStatus(row){
 if(!row?.progress?.valid||row.progress.status==="configuration-incomplete")return "configuration";
 if(row.progress.status==="completed")return "completed";
 if(Number(row.progress.daysRemaining)<=COORDINATION_THRESHOLDS.urgentDays)return "urgent";
 if(Number(row.progress.progressPercent)>=COORDINATION_THRESHOLDS.nearPercent)return "near";
 return "needed";
}
const priority=status=>({configuration:0,urgent:1,near:2,needed:3,completed:4}[status]??5);
export function sortCoordinationRows(rows,mode="priority"){
 const name=(a,b)=>String(a.customer.fullName||"").localeCompare(String(b.customer.fullName||""),"vi",{sensitivity:"base"});
 return [...rows].sort((a,b)=>{
  if(mode==="remaining-desc")return Number(b.progress.remainingEligibleSpend??-1)-Number(a.progress.remainingEligibleSpend??-1)||name(a,b);
  if(mode==="remaining-asc")return Number(a.progress.remainingEligibleSpend??Infinity)-Number(b.progress.remainingEligibleSpend??Infinity)||name(a,b);
  if(mode==="days")return Number(a.progress.daysRemaining??Infinity)-Number(b.progress.daysRemaining??Infinity)||name(a,b);
  if(mode==="customer")return name(a,b);
  return priority(coordinationDisplayStatus(a))-priority(coordinationDisplayStatus(b))||Number(a.progress.daysRemaining??Infinity)-Number(b.progress.daysRemaining??Infinity)||getProgramPriority(b.program)-getProgramPriority(a.program)||name(a,b);
 });
}
export function selectDefaultProgram(programs,currentId=""){
 const active=programs.filter(item=>item?.status==="active").sort((a,b)=>getProgramPriority(b)-getProgramPriority(a)||String(a?.name||"").localeCompare(String(b?.name||""),"vi"));
 return active.some(item=>item.id===currentId)?currentId:(active[0]?.id||"");
}

function programsFor(state,productId){return state.cashbackPrograms.filter(item=>item?.bankCardProductId===productId&&item.status==="active").sort((a,b)=>getProgramPriority(b)-getProgramPriority(a)||String(a?.name||"").localeCompare(String(b?.name||""),"vi"));}
function cardProducts(state){return state.cardProducts.filter(item=>item.id&&item.status!=="inactive").sort((a,b)=>String(a.cardId||"").localeCompare(String(b.cardId||""),"vi",{numeric:true,sensitivity:"base"}));}
function productLabel(state,product){const bank=state.banks.find(item=>item.id===product.bankId);return `${product.cardId} — ${bank?.name||"—"} · ${product.cardName||"—"} · ${product.cardBrand||product.network||"—"}`;}
function cycleLabel(product,customerCard){return (customerCard?.cashbackCycleModeOverride||product?.cashbackCycleMode)==="statement"?"Theo sao kê":"Theo tháng";}
function systemNote(row){if(row.progress.warning)return row.progress.warning;if(row.progress.status==="completed")return "Đã hoàn thành mục tiêu kỳ";if(row.progress.daysRemaining!=null)return `Còn ${row.progress.daysRemaining} ngày đến cuối kỳ`;return "";}
function summary(program,state){
 if(!program)return "";const pieces=[program.name,`${Number(program.rate)||0}%`,program.maxCashbackUnlimited?"Không giới hạn":`Max ${money(program.maxCashback)}`];
 if(!program.maxCashbackUnlimited)pieces.push(`Chi để max ${money(program.eligibleTarget)}`);
 if(program.transactionMethod)pieces.push(program.transactionMethod);
 const mode=getMccSelectionMode(program),excluded=(program.excludedMccCategoryIds||[]).filter(id=>state.mccCategories.some(item=>item.id===id));const mcc=mode==="all"?(excluded.length?`Tất cả MCC, trừ ${excluded.length} nhóm`:"Tất cả MCC"):program.mccCategoryIds?.map(id=>state.mccCategories.find(item=>item.id===id)?.name).filter(Boolean).join(", ");if(mcc)pieces.push(mcc);
 return pieces.join(" · ");
}
function reminderRows(state){
 const rows=buildCoordinationRows(state);const configuredCards=new Set(rows.map(row=>row.customerCard.id));
 const missing=state.customerCards.filter(card=>card.status==="active"&&!configuredCards.has(card.id)).map(card=>{const product=state.cardProducts.find(item=>item.id===card.cardProductId),customer=state.customers.find(item=>item.id===card.customerId);return product&&customer?{customer,customerCard:card,product,program:null,progress:{valid:false,status:"configuration-incomplete",warning:"Chưa khai báo chương trình hoàn tiền cho thẻ này."}}:null;}).filter(Boolean);
 return sortCoordinationRows([...rows.filter(row=>row.progress.status!=="completed"),...missing]);
}
function reminderCard(row){const status=coordinationDisplayStatus(row),remaining=row.progress.remainingEligibleSpend==null?"Chưa có mục tiêu":`Còn phải đánh ${money(row.progress.remainingEligibleSpend)}`,days=row.progress.daysRemaining==null?"—":`Còn ${row.progress.daysRemaining} ngày`;return `<article class="coord-reminder ${status}" data-reminder-card="${esc(row.customerCard.id)}|${esc(row.program?.id||"")}"><div><strong>${esc(row.customer.fullName)} · ${esc(row.product.cardId)}</strong><span>${esc(row.program?.name||"Chưa có chương trình")}</span></div><div class="coord-reminder-metrics"><b>${esc(remaining)}</b><span>${esc(days)}</span>${row.progress.warning?`<small>${esc(row.progress.warning)}</small>`:""}</div><button type="button" class="coord-link" data-open-reminder="${esc(row.customerCard.id)}|${esc(row.program?.id||"")}">Xem chi tiết →</button></article>`;}
function renderReminders(state){
 const rows=reminderRows(state),counts={needed:0,soon:0,configuration:0};rows.forEach(row=>{const status=coordinationDisplayStatus(row);if(["urgent","needed","near"].includes(status))counts.needed+=1;if(row.progress.valid&&Number(row.progress.daysRemaining)<=5)counts.soon+=1;if(status==="configuration")counts.configuration+=1;});
 const groups=[["urgent","Cần đánh gấp"],["needed","Cần đánh"],["near","Gần hoàn thành"],["configuration","Thiếu cấu hình"]];
 return `<div class="coord-kpis"><div class="kpi amber"><small>Cần đánh</small><strong>${counts.needed}</strong></div><div class="kpi red"><small>Sắp hết kỳ</small><strong>${counts.soon}</strong></div><div class="kpi blue"><small>Thiếu cấu hình</small><strong>${counts.configuration}</strong></div></div><div class="coord-reminder-groups">${groups.map(([key,title])=>{const items=rows.filter(row=>coordinationDisplayStatus(row)===key);return items.length?`<section><h2>${title}<span>${items.length}</span></h2><div class="coord-reminder-list">${items.map(reminderCard).join("")}</div></section>`:"";}).join("")||'<div class="empty panel">Chưa có dữ liệu để điều phối.</div>'}</div>`;
}
function detailRows(state){
 if(!coordinationUi.selectedCardProductId||!coordinationUi.selectedProgramId)return [];
 const query=normalize(coordinationUi.customerSearch);let rows=buildCoordinationRowsForSelection(state,{cardProductId:coordinationUi.selectedCardProductId,programId:coordinationUi.selectedProgramId});
 rows=rows.filter(row=>(!query||normalize(`${row.customer.fullName} ${row.customer.customerCode}`).includes(query))&&(!coordinationUi.statusFilter||coordinationDisplayStatus(row)===coordinationUi.statusFilter));return sortCoordinationRows(rows,coordinationUi.sortMode);
}
function noteCell(row){const manual=row.customerCard.notes||"",system=systemNote(row);return `<div class="coord-notes">${manual?`<span class="manual-note" title="${esc(manual)}">${esc(manual)}</span>`:""}${system?`<span class="system-reminder" title="${esc(system)}">${esc(system)}</span>`:""}${!manual&&!system?"—":""}</div>`;}
function customerRow(row){const status=coordinationDisplayStatus(row),target=row.progress.eligibleTarget==null?"Không giới hạn":money(row.progress.eligibleTarget),remaining=row.progress.remainingEligibleSpend==null?"—":money(row.progress.remainingEligibleSpend),period=row.progress.valid?`${formatDate(row.progress.cycleStart)} → ${formatDate(row.progress.cycleEnd)}`:"—";return `<tr data-coordination-row="${esc(row.customerCard.id)}" class="coord-row ${status}"><td data-label="Khách hàng"><strong>${esc(row.customer.fullName)}</strong>${row.customer.customerCode?`<small>${esc(row.customer.customerCode)}</small>`:""}</td><td data-label="Kỳ hiện tại">${esc(period)}</td><td data-label="Đã đánh">${money(row.progress.eligibleSpend||0)}</td><td data-label="Mục tiêu">${target}</td><td data-label="Còn thiếu">${remaining}</td><td data-label="Cashback dự kiến">${money(row.progress.cashbackEarned||0)}</td><td data-label="Còn ngày">${row.progress.daysRemaining??"—"}</td><td data-label="Trạng thái"><span class="coord-status ${status}">${STATUS[status]}</span></td><td data-label="Ghi chú">${noteCell(row)}</td></tr>`;}
function renderDetail(state){
 const products=cardProducts(state);if(!products.length)return '<div class="empty panel">Chưa có thẻ ngân hàng.</div>';
 if(!products.some(item=>item.id===coordinationUi.selectedCardProductId))coordinationUi.selectedCardProductId=products[0].id;
 const product=products.find(item=>item.id===coordinationUi.selectedCardProductId),programs=programsFor(state,product.id);coordinationUi.selectedProgramId=selectDefaultProgram(programs,coordinationUi.selectedProgramId);const program=programs.find(item=>item.id===coordinationUi.selectedProgramId),bank=state.banks.find(item=>item.id===product.bankId),owners=state.customerCards.filter(item=>item.status==="active"&&item.cardProductId===product.id),representative=owners[0];
 const picker=`<label class="coord-picker"><span>Tìm / chọn Card ID</span><input data-card-picker list="coord-card-options" autocomplete="off" value="${esc(product.cardId||"")}" placeholder="Nhập Card ID, ngân hàng, tên thẻ hoặc phôi"><datalist id="coord-card-options">${products.map(item=>`<option value="${esc(item.cardId)}">${esc(productLabel(state,item))}</option>`).join("")}</datalist></label>`;
 const info=`<section class="coord-card-info"><strong>${esc(product.cardId)}</strong><span><b>Ngân hàng:</b> ${esc(bank?.name||"—")}</span><span><b>Phôi:</b> ${esc(product.cardBrand||product.network||"—")}</span><span><b>Hình thức hoàn:</b> ${esc(cycleLabel(product,representative))}</span></section>`;
 const programPicker=`<label class="coord-program"><span>Chương trình hoàn tiền</span><select data-program-picker ${programs.length?"":"disabled"}>${programs.length?programs.map(item=>`<option value="${esc(item.id)}" ${item.id===coordinationUi.selectedProgramId?"selected":""}>${esc(item.name)}</option>`).join(""):'<option>Chưa có chương trình</option>'}</select></label>`;
 if(!programs.length)return `${picker}${info}${programPicker}<div class="empty panel">Chưa khai báo chương trình hoàn tiền cho thẻ này.</div>`;
 const rows=detailRows(state),toolbar=`<div class="coord-detail-toolbar"><input data-customer-search value="${esc(coordinationUi.customerSearch)}" placeholder="Tìm khách hàng..."><select data-status-filter><option value="">Trạng thái: Tất cả</option>${Object.entries(STATUS).map(([value,label])=>`<option value="${value}" ${value===coordinationUi.statusFilter?"selected":""}>${label}</option>`).join("")}</select><select data-sort-mode><option value="priority" ${coordinationUi.sortMode==="priority"?"selected":""}>Ưu tiên cần đánh</option><option value="remaining-desc" ${coordinationUi.sortMode==="remaining-desc"?"selected":""}>Còn thiếu nhiều nhất</option><option value="remaining-asc" ${coordinationUi.sortMode==="remaining-asc"?"selected":""}>Còn thiếu ít nhất</option><option value="days" ${coordinationUi.sortMode==="days"?"selected":""}>Còn ngày ít nhất</option><option value="customer" ${coordinationUi.sortMode==="customer"?"selected":""}>Khách hàng A → Z</option></select></div>`;
 const table=owners.length?`<div class="coord-table-wrap"><table class="coord-table"><thead><tr>${["Khách hàng","Kỳ hiện tại","Đã đánh","Mục tiêu","Còn thiếu","Cashback dự kiến","Còn ngày","Trạng thái","Ghi chú"].map(item=>`<th>${item}</th>`).join("")}</tr></thead><tbody>${rows.map(customerRow).join("")}</tbody></table>${!rows.length?'<div class="empty">Không có khách hàng phù hợp bộ lọc.</div>':""}</div>`:'<div class="empty panel">Chưa có khách hàng sở hữu Card ID này.</div>';
 return `${picker}${info}<div class="coord-program-row">${programPicker}<div class="coord-program-summary">${esc(summary(program,state))}</div></div>${toolbar}${table}`;
}
function recommendationModal(state){const overlay=document.createElement("div"),hasMcc=state.mccCategories.length>0,hasRows=buildCoordinationRows(state).length>0;overlay.className="feature-modal coord-recommend-modal";overlay.innerHTML=`<section class="modal-card"><div class="modal-head"><h2>Gợi ý đơn mới</h2><button type="button" data-close-recommend>×</button></div><form id="recommendForm"><div class="modal-body">${hasRows?"":'<div class="dependency-help full">Chưa có dữ liệu để điều phối.</div>'}<label class="field"><span>Số tiền đơn</span><input name="amount" inputmode="numeric" required></label><label class="field"><span>MCC</span><select name="mccCategoryId" ${hasMcc?"":"disabled"}><option value="">${hasMcc?"Tất cả":"Chưa có mã MCC"}</option>${state.mccCategories.map(item=>`<option value="${esc(item.id)}">${esc(item.name)} (${esc(item.codes.join(", "))})</option>`).join("")}</select></label><label class="field"><span>Hình thức giao dịch</span><select name="transactionMethod"><option value="">Tất cả</option>${["Online","Offline","Quẹt POS"].map(item=>`<option>${item}</option>`).join("")}</select></label></div><div id="recommendResults" class="coord-list"></div><div class="form-actions"><button type="button" class="secondary-btn" data-close-recommend>Đóng</button><button class="primary" ${hasRows&&hasMcc?"":"disabled"}>Gợi ý</button></div></form></section>`;document.body.append(overlay);overlay.querySelectorAll("[data-close-recommend]").forEach(button=>button.onclick=()=>overlay.remove());bindVndInput(overlay.querySelector('[name="amount"]'));overlay.querySelector("form").onsubmit=event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget)),items=recommendOrders(state,{...values,amount:parseMoney(values.amount)});overlay.querySelector("#recommendResults").innerHTML=items.slice(0,10).map((item,index)=>`<div><strong>${index===0?"Ưu tiên: ":""}${esc(item.customer.fullName)} · ${esc(item.product.cardId)} · ${esc(item.program.name)}</strong><span>Còn trước đơn ${item.progress.remainingEligibleSpend==null?"—":money(item.progress.remainingEligibleSpend)} · đơn hợp lệ ${money(item.eligibleAmount)} · cashback tăng ${money(item.incrementalCashback)} · còn sau đơn ${item.remainingAfter==null?"—":money(item.remainingAfter)}</span></div>`).join("")||'<div class="empty">Không có thẻ/chương trình phù hợp.</div>';};}
function focusRow(){if(!coordinationUi.focusCustomerCardId)return;requestAnimationFrame(()=>{const row=document.querySelector(`[data-coordination-row="${CSS.escape(coordinationUi.focusCustomerCardId)}"]`);if(!row)return;row.classList.add("coord-focus");row.scrollIntoView({behavior:"smooth",block:"center"});setTimeout(()=>row.classList.remove("coord-focus"),1800);coordinationUi.focusCustomerCardId="";});}

export function renderCoordinationWorkspace(state){
 const root=document.querySelector("#view-coordination");if(!root)return;root.innerHTML=`<div class="coord-workspace"><div class="coord-head"><div class="coord-tabs" role="tablist"><button type="button" data-coord-tab="reminders" class="${coordinationUi.activeTab==="reminders"?"active":""}">Nhắc nhở</button><button type="button" data-coord-tab="details" class="${coordinationUi.activeTab==="details"?"active":""}">Chi tiết</button></div><button type="button" class="primary coord-recommend-open">Gợi ý đơn mới</button></div><section class="coord-tab-panel">${coordinationUi.activeTab==="reminders"?renderReminders(state):renderDetail(state)}</section></div>`;
 root.querySelectorAll("[data-coord-tab]").forEach(button=>button.onclick=()=>{coordinationUi.activeTab=button.dataset.coordTab;renderCoordinationWorkspace(state);});root.querySelector(".coord-recommend-open").onclick=()=>recommendationModal(state);
 root.querySelectorAll("[data-open-reminder], [data-reminder-card]").forEach(element=>element.onclick=event=>{if(element.hasAttribute("data-reminder-card")&&event.target.closest("button"))return;const [cardId,programId]=(element.dataset.openReminder||element.dataset.reminderCard).split("|");const card=state.customerCards.find(item=>item.id===cardId);if(!card)return;coordinationUi.activeTab="details";coordinationUi.selectedCardProductId=card.cardProductId;coordinationUi.selectedProgramId=programId;coordinationUi.focusCustomerCardId=cardId;coordinationUi.customerSearch="";coordinationUi.statusFilter="";renderCoordinationWorkspace(state);focusRow();});
 const cardPicker=root.querySelector("[data-card-picker]");if(cardPicker)cardPicker.onchange=()=>{const value=normalize(cardPicker.value),product=cardProducts(state).find(item=>normalize(item.cardId)===value||normalize(productLabel(state,item))===value);if(!product)return;coordinationUi.selectedCardProductId=product.id;coordinationUi.selectedProgramId="";coordinationUi.focusCustomerCardId="";renderCoordinationWorkspace(state);};
 const programPicker=root.querySelector("[data-program-picker]");if(programPicker)programPicker.onchange=()=>{coordinationUi.selectedProgramId=programPicker.value;renderCoordinationWorkspace(state);};
 const search=root.querySelector("[data-customer-search]");if(search)search.oninput=()=>{coordinationUi.customerSearch=search.value;const rows=detailRows(state),body=root.querySelector(".coord-table tbody");if(body)body.innerHTML=rows.map(customerRow).join("");};
 const status=root.querySelector("[data-status-filter]");if(status)status.onchange=()=>{coordinationUi.statusFilter=status.value;renderCoordinationWorkspace(state);};const sort=root.querySelector("[data-sort-mode]");if(sort)sort.onchange=()=>{coordinationUi.sortMode=sort.value;renderCoordinationWorkspace(state);};
 root.querySelectorAll(".coord-table tbody tr").forEach(row=>{row.tabIndex=0;row.onclick=()=>row.classList.toggle("coord-expanded");row.onkeydown=event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();row.classList.toggle("coord-expanded");}};});
}
