import {buildMatrix,formatMatrixCustomerName,matrixOrderPreset} from './matrix-engine.js?v=20260906-matrix-v1';
import {formatMoney} from './money.js';
import {formatDate} from './date.js';

const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normalize=value=>String(value||'').toLocaleLowerCase('vi').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d');
const money=value=>value==null?'Không giới hạn':formatMoney(value,true);
const compact=value=>value==null?'∞':Number(value)>=1000000?`${+(Number(value)/1000000).toFixed(2)}tr`:Number(value)>=1000?`${+(Number(value)/1000).toFixed(1)}k`:String(Number(value)||0);
const labels={AVAILABLE:'Chưa đánh / Có thể đánh đơn',IN_PROGRESS:'Đang thực hiện chỉ tiêu',COMPLETED:'Đã đủ chỉ tiêu trong kỳ',NOT_APPLICABLE:'Không sở hữu thẻ'};
const filters={q:'',bank:'',product:'',program:'',status:'',actionable:false,customers:null};
const period=cell=>cell.cycle?.valid?`${formatDate(cell.cycle.start)} - ${formatDate(cell.cycle.end)}`:'Chưa xác định';
function tooltip(cell){return [cell.customer.fullName,cell.product.cardId,cell.program.name,`Kỳ: ${period(cell)}`,`Chỉ tiêu: ${money(cell.progress?.eligibleTarget)}`,`Đã đánh: ${money(cell.progress?.eligibleSpend||0)}`,`Còn thiếu: ${money(cell.progress?.remainingEligibleSpend)}`,cell.warning||labels[cell.status]].join('\n');}
const shortBrand=value=>({MASTERCARD:'MASTER','MASTER CARD':'MASTER','AMERICAN EXPRESS':'AMEX'}[String(value||'').toUpperCase()]||String(value||'—').toUpperCase());
const cellText=cell=>cell.status==='NOT_APPLICABLE'?'—':!cell.status?'⚠':cell.progress.eligibleSpend===0?'0':`${compact(cell.progress.eligibleSpend)}/${compact(cell.progress.eligibleTarget)}`;

export function mountMatrix(root,getState,actions={}){
 const model=buildMatrix(getState());let visibleRows,visibleCustomers;
 const selected=customer=>filters.customers===null||filters.customers.has(customer.id);
 const matches=cell=>(!filters.status||cell.status===filters.status)&&(!filters.actionable||['AVAILABLE','IN_PROGRESS'].includes(cell.status));
 function draw(){
  const state=getState();visibleCustomers=model.customers.filter(selected);
  const q=normalize(filters.q);
  visibleRows=model.rows.filter(row=>(!filters.bank||row.bank?.id===filters.bank)&&(!filters.product||row.product.id===filters.product)&&(!filters.program||row.program.id===filters.program)&&(!q||normalize([row.bank?.name,row.product.cardId,row.product.cardBrand,row.program.name].join(' ')).includes(q)));
  if(filters.status||filters.actionable){visibleRows=visibleRows.filter(row=>row.cells.some(cell=>selected(cell.customer)&&matches(cell)));visibleCustomers=visibleCustomers.filter(customer=>visibleRows.some(row=>row.cells.some(cell=>cell.customer.id===customer.id&&matches(cell))));}
  const select=(key,label,items)=>`<select data-matrix-filter="${key}" aria-label="${label}"><option value="">${label}: Tất cả</option>${items.map(([id,name])=>`<option value="${esc(id)}" ${filters[key]===id?'selected':''}>${esc(name)}</option>`).join('')}</select>`;
  root.innerHTML=`<div class="toolbar matrix-toolbar"><input data-matrix-search class="search" aria-label="Tìm ma trận" placeholder="Tìm ngân hàng, Card ID, chương trình..." value="${esc(filters.q)}">${select('bank','Ngân hàng',state.banks.map(x=>[x.id,x.name]))}${select('product','Card ID',state.cardProducts.map(x=>[x.id,x.cardId]))}${select('program','Chương trình',state.cashbackPrograms.map(x=>[x.id,x.name]))}<details class="matrix-customer-picker"><summary>Khách hàng · ${filters.customers===null?'Tất cả':model.customers.filter(selected).length} ▾</summary><div class="matrix-customer-panel"><input data-matrix-customer-search placeholder="Tìm tên khách hàng" aria-label="Tìm tên khách hàng"><div class="matrix-pick-actions"><button type="button" data-matrix-all>Chọn tất cả</button><button type="button" data-matrix-none>Bỏ chọn tất cả</button></div>${model.customers.map(customer=>`<label data-matrix-customer-label><input type="checkbox" value="${esc(customer.id)}" ${selected(customer)?'checked':''}>${esc(customer.fullName)}</label>`).join('')}</div></details>${select('status','Trạng thái',[['AVAILABLE','Xanh - Chưa đánh'],['IN_PROGRESS','Vàng - Đang đánh'],['COMPLETED','Đỏ - Đã đủ chỉ tiêu']])}<label class="matrix-actionable"><input type="checkbox" data-matrix-actionable ${filters.actionable?'checked':''}>Chỉ hiện cần xử lý</label><button type="button" data-matrix-clear>Xóa lọc</button></div><div class="matrix-legend"><span class="AVAILABLE">Xanh: Chưa đánh</span><span class="IN_PROGRESS">Vàng: Đang đánh</span><span class="COMPLETED">Đỏ: Đã đủ chỉ tiêu</span><span>— Không sở hữu · ⚠ Cần kiểm tra cấu hình</span></div><div data-matrix-content></div>`;
  drawContent();
  root.querySelector('[data-matrix-search]').oninput=event=>{const position=event.target.selectionStart;filters.q=event.target.value;draw();const input=root.querySelector('[data-matrix-search]');input.focus();input.setSelectionRange(position,position);};
  root.querySelectorAll('[data-matrix-filter]').forEach(input=>input.onchange=()=>{filters[input.dataset.matrixFilter]=input.value;draw();});
  root.querySelector('[data-matrix-actionable]').onchange=event=>{filters.actionable=event.target.checked;draw();};
  root.querySelector('[data-matrix-clear]').onclick=()=>{Object.assign(filters,{q:'',bank:'',product:'',program:'',status:'',actionable:false,customers:null});draw();};
  const redrawPicker=()=>{draw();root.querySelector('.matrix-customer-picker').open=true;};
  root.querySelector('[data-matrix-all]').onclick=()=>{filters.customers=null;redrawPicker();};
  root.querySelector('[data-matrix-none]').onclick=()=>{filters.customers=new Set();redrawPicker();};
  root.querySelector('[data-matrix-customer-search]').oninput=event=>root.querySelectorAll('[data-matrix-customer-label]').forEach(label=>label.hidden=!normalize(label.textContent).includes(normalize(event.target.value)));
  root.querySelectorAll('[data-matrix-customer-label] input').forEach(input=>input.onchange=()=>{if(filters.customers===null)filters.customers=new Set(model.customers.map(customer=>customer.id));input.checked?filters.customers.add(input.value):filters.customers.delete(input.value);redrawPicker();});
 }
 function drawContent(){
  const content=root.querySelector('[data-matrix-content]');
  if(!visibleRows.length||!visibleCustomers.length){content.innerHTML='<div class="empty panel">Không có chương trình / khách hàng phù hợp bộ lọc.</div>';return;}
  const customerIds=new Set(visibleCustomers.map(customer=>customer.id));
  const markup=(cell,rowIndex,index)=>{const title=esc(tooltip(cell));return cell.status==='NOT_APPLICABLE'?`<span class="matrix-cell NOT_APPLICABLE" title="${title}">—</span>`:!matches(cell)?'<span class="matrix-cell matrix-filtered" title="Ẩn bởi bộ lọc">·</span>':`<button type="button" class="matrix-cell ${cell.status||'matrix-warning'}" data-matrix-cell="${rowIndex}:${index}" title="${title}" aria-label="${title}">${esc(cellText(cell)).replace('/', '/<wbr>')}</button>`;};
  content.innerHTML=`<div class="matrix-scroll"><table class="matrix-table" style="--matrix-customer-count:${visibleCustomers.length}"><thead><tr>${['Ngân hàng','Card ID','Phôi','Chương trình hoàn tiền'].map(label=>`<th scope="col">${label}</th>`).join('')}${visibleCustomers.map(customer=>`<th scope="col" title="${esc(customer.fullName)}"><span class="matrix-header-name">${esc(formatMatrixCustomerName(customer.fullName))}</span></th>`).join('')}</tr></thead><tbody>${visibleRows.map((row,r)=>`<tr class="${r===0||visibleRows[r-1].product.id!==row.product.id?'matrix-group-start':''}"><td title="${esc(row.bank?.name||'—')}">${esc(row.bank?.code||row.bank?.name||'—')}</td><td title="${esc(row.product.cardId)}">${esc(row.product.cardId)}</td><td title="${esc(row.product.cardBrand||row.product.network||'—')}">${esc(shortBrand(row.product.cardBrand||row.product.network))}</td><td title="${esc(row.program.name)}"><span class="matrix-program-name">${esc(row.program.name)}</span></td>${row.cells.map((cell,c)=>customerIds.has(cell.customer.id)?`<td>${markup(cell,r,c)}</td>`:'').join('')}</tr>`).join('')}</tbody></table></div><div class="matrix-stacked">${visibleRows.map((row,r)=>`<details class="panel" open><summary><strong>${esc(row.product.cardId)}</strong> · ${esc(row.program.name)}<small>${esc(row.bank?.name||'—')} · ${esc(row.product.cardBrand||row.product.network||'—')}</small></summary><div>${row.cells.map((cell,c)=>customerIds.has(cell.customer.id)&&(!filters.actionable&&!filters.status||matches(cell))?`<div class="matrix-mobile-cell"><span title="${esc(cell.customer.fullName)}">${esc(formatMatrixCustomerName(cell.customer.fullName))}</span>${markup(cell,r,c)}</div>`:'').join('')}</div></details>`).join('')}</div>`;
  content.querySelectorAll('[data-matrix-cell]').forEach(button=>button.onclick=()=>{const [r,c]=button.dataset.matrixCell.split(':').map(Number);const row=visibleRows[r],customerId=row.cells[c].customer.id;const fresh=buildMatrix(getState()).rows.find(item=>item.program.id===row.program.id)?.cells.find(cell=>cell.customer.id===customerId);if(fresh)openMatrixModal(fresh,getState(),actions,button);});
 }
 draw();
}

function openMatrixModal(cell,state,actions,trigger){
 const overlay=document.createElement('div'),p=cell.progress||{},completed=cell.status==='COMPLETED',actionable=['AVAILABLE','IN_PROGRESS'].includes(cell.status),previous=document.activeElement;
 overlay.className='feature-modal matrix-modal';overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-labelledby','matrix-modal-title');
 const details=[['Khách hàng',cell.customer.fullName],['Card ID',cell.product.cardId],['Ngân hàng',state.banks.find(bank=>bank.id===cell.product.bankId)?.name||'—'],['Phôi',cell.product.cardBrand||cell.product.network||'—'],['Chương trình hoàn tiền',cell.program.name],['% Cashback',p.conditionProgress?.map(condition=>`${condition.rate}%`).join(' / ')||`${cell.program.rate}%`],['Max Cashback',money(p.maxCashback)],['Chỉ tiêu',money(p.eligibleTarget)],['Kỳ hiện tại',period(cell)],['Đã đánh',money(p.eligibleSpend||0)],['Còn thiếu',money(p.remainingEligibleSpend)],['Cashback dự kiến',money(p.cashbackEstimated||0)]];
 if(p.totalTarget!=null)details.push(['Chi tiêu tổng',`${money(p.totalCardSpend)} / ${money(p.totalTarget)}`]);
 overlay.innerHTML=`<section class="modal-card"><div class="modal-head"><h2 id="matrix-modal-title">${esc(labels[cell.status]||'Cần kiểm tra cấu hình')}</h2><button type="button" data-close aria-label="Đóng">×</button></div><div class="matrix-modal-body"><dl>${details.map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${esc(value)}</dd></div>`).join('')}</dl>${p.conditionProgress?.length>1?`<p>Điều kiện ${esc(p.combineOperator)}: ${p.conditionProgress.map(condition=>`${condition.rate}%: ${money(condition.eligibleSpend)} / ${money(condition.target)}`).map(esc).join(' · ')}</p>`:''}${p.progressPercent!=null?`<label class="matrix-progress">Tiến độ: ${Math.round(p.progressPercent*10)/10}%<progress max="100" value="${p.progressPercent}"></progress></label>`:''}${cell.warning||p.warning?`<p class="dependency-help">${esc(cell.warning||p.warning)}</p>`:''}${completed?`<div class="table-wrap"><table><thead><tr><th>Ngày</th><th>Tiền đơn</th></tr></thead><tbody>${cell.transactions.map(tx=>`<tr><td>${formatDate(tx.date)}</td><td>${money(tx.amount)}</td></tr>`).join('')}</tbody><tfoot><tr><th>Tổng</th><td>${money(cell.transactions.reduce((sum,tx)=>sum+Number(tx.amount||0),0))}</td></tr></tfoot></table></div>`:''}<p>${completed?'Bạn có muốn xem lại giao dịch chi tiết không?':actionable?cell.status==='AVAILABLE'?'Bạn có muốn đánh đơn luôn không?':'Bạn có muốn đánh thêm đơn không?':'Vui lòng kiểm tra thẻ khách hàng và cấu hình chương trình.'}</p></div><div class="form-actions"><button type="button" class="secondary-btn" data-close>Không</button>${actionable||completed?`<button type="button" class="primary" data-matrix-action>${completed?'Xem giao dịch':cell.status==='AVAILABLE'?'Đánh đơn':'Đánh thêm đơn'}</button>`:''}</div></section>`;
 const close=()=>{overlay.remove();if(previous?.isConnected)previous.focus();else if(trigger?.isConnected)trigger.focus();};
 overlay.querySelectorAll('[data-close]').forEach(button=>button.onclick=close);
 overlay.onclick=event=>{if(event.target===overlay)close();};
 overlay.onkeydown=event=>{if(event.key==='Escape')close();if(event.key==='Tab'){const buttons=[...overlay.querySelectorAll('button')],first=buttons[0],last=buttons.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}};
 const action=overlay.querySelector('[data-matrix-action]');if(action)action.onclick=()=>{close();if(completed)actions.viewTransactions?.(cell);else actions.addOrder?.(matrixOrderPreset(cell,state),cell);};
 document.body.append(overlay);overlay.querySelector('[data-close]').focus();
}
