const PREF_KEY="cardflow-host-table-column-widths-v1";
const MIN_WIDTH=56;
const read=()=>{try{return JSON.parse(localStorage.getItem(PREF_KEY)||"{}");}catch{return {};}};
const write=value=>{try{localStorage.setItem(PREF_KEY,JSON.stringify(value));}catch{}};
const tableKey=(table,index)=>`${table.closest(".view")?.id||"global"}:${table.dataset.entity||table.dataset.featureTable||table.className||"table"}:${index}`;
const columnKey=(th,index)=>th.dataset.columnKey||th.textContent.trim();
const legacyColumnKey=(th,index)=>`${index}:${th.textContent.trim()}`;
const ensureColgroup=(table,count)=>{let colgroup=[...table.children].find(node=>node.tagName==="COLGROUP");if(!colgroup){colgroup=document.createElement("colgroup");table.insertBefore(colgroup,table.firstElementChild);}while(colgroup.children.length<count)colgroup.append(document.createElement("col"));return [...colgroup.children].slice(0,count);};
const apply=(table,th,index,width)=>{const value=Math.max(MIN_WIDTH,Math.round(width)),col=ensureColgroup(table,table.querySelectorAll("thead th").length)[index];table.style.tableLayout="fixed";table.style.width="max-content";table.style.minWidth="max-content";col.style.width=`${value}px`;col.style.minWidth=`${value}px`;th.style.width=`${value}px`;th.style.minWidth=`${value}px`;};
export function attachResizableTables(root=document){if(window.matchMedia?.("(max-width:767px)").matches)return;const saved=read();root.querySelectorAll("table").forEach((table,tableIndex)=>{if(table.dataset.noResize!==undefined||table.closest(".matrix-stacked")||table.classList.contains("matrix-table"))return;const headers=[...table.querySelectorAll("thead th")];if(!headers.length)return;const key=tableKey(table,tableIndex);headers.forEach((th,index)=>{if(th.querySelector("[data-table-resize-handle]"))return;const stableKey=columnKey(th,index),stored=saved[key]?.[stableKey]||saved[key]?.[legacyColumnKey(th,index)];if(stored)apply(table,th,index,stored);const handle=document.createElement("span");handle.className="table-resize-handle";handle.dataset.tableResizeHandle="";handle.setAttribute("aria-label",`Kéo để đổi độ rộng ${th.textContent.trim()}`);th.append(handle);handle.addEventListener("pointerdown",event=>{event.preventDefault();event.stopPropagation();const startX=event.clientX,startWidth=th.getBoundingClientRect().width;document.body.classList.add("table-resizing");const move=e=>apply(table,th,index,startWidth+e.clientX-startX);const end=()=>{document.body.classList.remove("table-resizing");saved[key]||=(saved[key]={});saved[key][stableKey]=Math.round(th.getBoundingClientRect().width);write(saved);window.removeEventListener("pointermove",move);};window.addEventListener("pointermove",move);window.addEventListener("pointerup",end,{once:true});});});});}
